spring:
  application:
    name: CarRental
  datasource:
    url: jdbc:postgresql://localhost:5432/JEE_DB
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/JEE
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
